# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'safetycheck.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_safetycheck(object):
    def setupUi(self, safetycheck):
        safetycheck.setObjectName("safetycheck")
        safetycheck.resize(525, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(safetycheck)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(safetycheck)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.safetyCheckButtons = QtWidgets.QDialogButtonBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.safetyCheckButtons.setFont(font)
        self.safetyCheckButtons.setStyleSheet("")
        self.safetyCheckButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.safetyCheckButtons.setCenterButtons(True)
        self.safetyCheckButtons.setObjectName("safetyCheckButtons")
        self.gridLayout.addWidget(self.safetyCheckButtons, 9, 0, 1, 3)
        self.dutGain = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dutGain.setFont(font)
        self.dutGain.setObjectName("dutGain")
        self.gridLayout.addWidget(self.dutGain, 6, 1, 1, 1)
        self.rfOutputLabel_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfOutputLabel_2.setFont(font)
        self.rfOutputLabel_2.setObjectName("rfOutputLabel_2")
        self.gridLayout.addWidget(self.rfOutputLabel_2, 6, 0, 1, 1)
        self.rfInputLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfInputLabel.setFont(font)
        self.rfInputLabel.setObjectName("rfInputLabel")
        self.gridLayout.addWidget(self.rfInputLabel, 4, 0, 1, 1)
        self.paprCheck = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.paprCheck.setFont(font)
        self.paprCheck.setObjectName("paprCheck")
        self.gridLayout.addWidget(self.paprCheck, 8, 1, 1, 1)
        self.dutPower = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dutPower.setFont(font)
        self.dutPower.setObjectName("dutPower")
        self.gridLayout.addWidget(self.dutPower, 5, 1, 1, 1)
        self.rfOutputLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfOutputLabel.setFont(font)
        self.rfOutputLabel.setObjectName("rfOutputLabel")
        self.gridLayout.addWidget(self.rfOutputLabel, 5, 0, 1, 1)
        self.rfInputLabel_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfInputLabel_4.setFont(font)
        self.rfInputLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.rfInputLabel_4.setObjectName("rfInputLabel_4")
        self.gridLayout.addWidget(self.rfInputLabel_4, 8, 2, 1, 1)
        self.dutMaxPower = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dutMaxPower.setFont(font)
        self.dutMaxPower.setObjectName("dutMaxPower")
        self.gridLayout.addWidget(self.dutMaxPower, 4, 1, 1, 1)
        self.rfInputLabel_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfInputLabel_2.setFont(font)
        self.rfInputLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.rfInputLabel_2.setObjectName("rfInputLabel_2")
        self.gridLayout.addWidget(self.rfInputLabel_2, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.rfOutputLabel_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfOutputLabel_3.setFont(font)
        self.rfOutputLabel_3.setObjectName("rfOutputLabel_3")
        self.gridLayout.addWidget(self.rfOutputLabel_3, 8, 0, 1, 1)
        self.rfInputLabel_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfInputLabel_3.setFont(font)
        self.rfInputLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.rfInputLabel_3.setObjectName("rfInputLabel_3")
        self.gridLayout.addWidget(self.rfInputLabel_3, 6, 2, 1, 1)
        self.rfInputLabel_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rfInputLabel_5.setFont(font)
        self.rfInputLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.rfInputLabel_5.setObjectName("rfInputLabel_5")
        self.gridLayout.addWidget(self.rfInputLabel_5, 4, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(safetycheck)
        QtCore.QMetaObject.connectSlotsByName(safetycheck)

    def retranslateUi(self, safetycheck):
        _translate = QtCore.QCoreApplication.translate
        safetycheck.setWindowTitle(_translate("safetycheck", "safetycheck"))
        self.rfOutputLabel_2.setText(_translate("safetycheck", "DUT Estimated Gain:"))
        self.rfInputLabel.setText(_translate("safetycheck", "DUT Max. Output Power:"))
        self.rfOutputLabel.setText(_translate("safetycheck", "DUT Mean Input Power:"))
        self.rfInputLabel_4.setText(_translate("safetycheck", "dB"))
        self.rfInputLabel_2.setText(_translate("safetycheck", "dBm"))
        self.label_4.setText(_translate("safetycheck", "Before continuing to Step 2, please provide the following information:"))
        self.rfOutputLabel_3.setText(_translate("safetycheck", "Input Signal PAPR:"))
        self.rfInputLabel_3.setText(_translate("safetycheck", "dB"))
        self.rfInputLabel_5.setText(_translate("safetycheck", "dBm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    safetycheck = QtWidgets.QDialog()
    ui = Ui_safetycheck()
    ui.setupUi(safetycheck)
    safetycheck.show()
    sys.exit(app.exec_())

